#!/usr/bin/env python3
"""EMBERFALL — music compiler.

Songs are written as (note, beats) tuples per channel; emits src/gen/songs.s
with the NTSC period table and event streams for the driver in sound.s.
Stream format: [note-index, frames] pairs; 'r' = rest ($FF), loop with $FE.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# note index 0 = A1 (55 Hz), chromatic upward
NAMES = ["a", "a+", "b", "c", "c+", "d", "d+", "e", "f", "f+", "g", "g+"]
N_NOTES = 60

def idx(note):
    """'c4' -> semitones above A1. octave numbering: c4..b4 contains a4."""
    name = note[:-1]
    octv = int(note[-1])
    s = NAMES.index(name)
    # a,a+,b belong to octave o at index (o-1)*12 + s; c..g+ at (o-2)*12 + s
    if s < 3:
        return (octv - 1) * 12 + s
    return (octv - 2) * 12 + s

def period(i):
    f = 55.0 * (2.0 ** (i / 12.0))
    return round(1789773 / (16 * f)) - 1

def stream(events, beat_frames):
    out = []
    for note, beats in events:
        dur = round(beats * beat_frames)
        while dur > 0:
            d = min(dur, 255)
            out.append(0xFF if note == "r" else idx(note))
            out.append(d)
            dur -= d
    out.append(0xFE)
    return out

Q = 1        # quarter
H = 2
W = 4
E = 0.5

# --------------------------------------------------------------------- songs
FIELD_MEL = [
    ("a4",Q),("b4",Q),("c5",Q),("e5",Q),
    ("d5",Q),("c5",Q),("b4",H),
    ("g4",Q),("a4",Q),("b4",Q),("d5",Q),
    ("c5",Q),("b4",Q),("a4",H),
    ("e5",Q),("d5",Q),("c5",Q),("b4",Q),
    ("c5",Q),("d5",Q),("e5",H),
    ("a4",Q),("c5",Q),("b4",Q),("g4",Q),
    ("a4",W),
]
FIELD_BAS = [
    ("a2",H),("a3",H), ("f2",H),("g2",H),
    ("g2",H),("b2",H), ("a2",H),("e2",H),
    ("c3",H),("b2",H), ("a2",H),("e3",H),
    ("f2",H),("g2",H), ("a2",H),("a2",H),
]
TOWN_MEL = [
    ("c4",Q),("e4",Q),("g4",Q),("e4",Q),
    ("a4",Q),("g4",Q),("e4",H),
    ("f4",Q),("a4",Q),("g4",Q),("e4",Q),
    ("d4",Q),("e4",Q),("c4",H),
]
TOWN_BAS = [
    ("c3",H),("c3",H), ("f2",H),("g2",H),
    ("f2",H),("c3",H), ("g2",H),("c3",H),
]
CAVE_MEL = [
    ("a3",H),("c4",H), ("b3",H),("g3",H),
    ("a3",H),("d4",H), ("b3",W),
    ("a3",H),("c4",H), ("e4",H),("d4",H),
    ("c4",H),("b3",H), ("a3",W),
]
CAVE_BAS = [
    ("a2",W),("e2",W),("d2",W),("e2",W),
    ("a2",W),("c3",W),("d2",W),("e2",W),
]
BATTLE_MEL = [
    ("a4",E),("a4",E),("c5",E),("a4",E),("d5",E),("c5",E),("b4",E),("g4",E),
    ("a4",E),("a4",E),("c5",E),("d5",E),("e5",Q),("c5",E),("a4",E),
    ("f4",E),("f4",E),("a4",E),("f4",E),("g4",E),("g4",E),("b4",E),("g4",E),
    ("a4",E),("c5",E),("b4",E),("g4",E),("a4",H),
]
BATTLE_BAS = [
    ("a2",Q),("a2",Q),("a2",Q),("a2",Q),
    ("a2",Q),("a2",Q),("a2",Q),("a2",Q),
    ("f2",Q),("f2",Q),("g2",Q),("g2",Q),
    ("a2",Q),("a2",Q),("e2",Q),("e2",Q),
]
TITLE_MEL = [
    ("a3",Q),("c4",Q),("e4",Q),("a4",Q),
    ("g4",H),("e4",H),
    ("f4",Q),("e4",Q),("d4",Q),("e4",Q),
    ("c4",W),
    ("a3",Q),("c4",Q),("e4",Q),("g4",Q),
    ("a4",H),("e4",H),
    ("d4",Q),("e4",Q),("c4",Q),("b3",Q),
    ("a3",W),
]
TITLE_BAS = [
    ("a2",W),("c3",W),("f2",W),("g2",W),
    ("a2",W),("c3",W),("d3",W),("a2",W),
]
END_MEL = [
    ("c5",Q),("g4",Q),("e4",Q),("g4",Q),
    ("a4",Q),("g4",Q),("c5",H),
    ("f4",Q),("a4",Q),("g4",Q),("e4",Q),
    ("d4",Q),("e4",Q),("c4",H),
]
END_BAS = [
    ("c3",H),("g2",H), ("a2",H),("g2",H),
    ("f2",H),("c3",H), ("g2",H),("c3",H),
]

# id order must match MUS_* in defs.inc: FIELD TOWN CAVE TITLE BATTLE END
SONGS = [
    ("field",  FIELD_MEL,  FIELD_BAS,  24),
    ("town",   TOWN_MEL,   TOWN_BAS,   28),
    ("cave",   CAVE_MEL,   CAVE_BAS,   40),
    ("title",  TITLE_MEL,  TITLE_BAS,  26),
    ("battle", BATTLE_MEL, BATTLE_BAS, 15),
    ("end",    END_MEL,    END_BAS,    24),
]

os.makedirs(os.path.join(ROOT, "src", "gen"), exist_ok=True)
with open(os.path.join(ROOT, "src", "gen", "songs.s"), "w") as f:
    f.write("; generated by tools/music.py — do not edit\n")
    f.write('.segment "RODATA"\n')
    f.write("note_lo:\n")
    for i in range(N_NOTES):
        f.write(f"  .byte <{period(i)}\n")
    f.write("note_hi:\n")
    for i in range(N_NOTES):
        f.write(f"  .byte >{period(i)}\n")
    for name, mel, bas, bf in SONGS:
        for ch, ev in (("m", mel), ("b", bas)):
            data = stream(ev, bf)
            f.write(f"song_{name}_{ch}:\n")
            for k in range(0, len(data), 16):
                f.write("  .byte " + ",".join(f"${b:02X}" for b in data[k:k+16]) + "\n")
    f.write("song_tbl:\n")
    for name, _, _, _ in SONGS:
        f.write(f"  .word song_{name}_m, song_{name}_b\n")

for i in (0, 12, 24, 36, 48):
    assert period(i) < 2048
print("songs.s emitted")
